# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/arty/IRIG_READER_LOGIC/archived_pro/archived_pro.cache/wt [current_project]
set_property parent.project_path G:/arty/IRIG_READER_LOGIC/archived_pro/archived_pro.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  G:/arty/IRIG_READER_LOGIC/archived_pro/archived_pro.srcs/sources_1/imports/irig-decoder-master/bcd_decoder.v
  G:/arty/IRIG_READER_LOGIC/archived_pro/archived_pro.srcs/sources_1/imports/new/irig_symbol_decode.v
  G:/arty/IRIG_READER_LOGIC/archived_pro/archived_pro.srcs/sources_1/imports/irig-decoder-master/irig_state.v
  G:/arty/IRIG_READER_LOGIC/archived_pro/archived_pro.srcs/sources_1/imports/irig-decoder-master/irig_timestamp.v
  G:/arty/IRIG_READER_LOGIC/archived_pro/archived_pro.srcs/sources_1/imports/irig-decoder-master/irig.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top irig -part xc7a35tcpg236-1


write_checkpoint -force -noxdef irig.dcp

catch { report_utilization -file irig_utilization_synth.rpt -pb irig_utilization_synth.pb }
