# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/my_project_reader/seq_detector/seq_detector.cache/wt [current_project]
set_property parent.project_path G:/my_project_reader/seq_detector/seq_detector.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
read_verilog -library xil_defaultlib G:/my_project_reader/seq_detector/seq_detector.srcs/sources_1/new/seq_dector.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/my_project_reader/seq_detector/seq_detector.srcs/constrs_1/imports/my_project_reader/Arty_Master.xdc
set_property used_in_implementation false [get_files G:/my_project_reader/seq_detector/seq_detector.srcs/constrs_1/imports/my_project_reader/Arty_Master.xdc]


synth_design -top seq_dector -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef seq_dector.dcp

catch { report_utilization -file seq_dector_utilization_synth.rpt -pb seq_dector_utilization_synth.pb }
